name: Create Feature Branch (Website)

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - 'staging'
      - 'release/**'
      - 'main'

jobs:
  caller-checks:
    uses: EngineerincioOrg/Infra_CI_Templates/.github/workflows/reusable-checks.yml@main
    secrets:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
    with:
      main_branch: staging
      node_version: 20
      validate_pr: true
      source_branch: ${{ github.head_ref }}
      target_branch: ${{ github.base_ref }}