name: Checks (Website)

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - staging
      - main
      - release/*
      - hotfix/*

jobs:
  caller-checks:
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: EngineerincioOrg/Infra_CI_Templates/.github/workflows/reusable-checks.yml@main
    with:
      main_branch: staging
      node_version: 20
      checkout_ref: ${{ github.event.pull_request.head.sha || github.sha }}
      validate_pr: true
      source_branch: ${{ github.head_ref }}
      target_branch: ${{ github.base_ref }}
    secrets:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}