name: Create Feature Branch (Website)

on:
  workflow_dispatch:
    inputs:
      jira_key:
        description: 'Jira Key (e.g., DEV-42) to create a branch for.'
        required: true
        type: string
      base_branch:
        description: 'The branch from which to create the new feature branch.'
        required: false
        type: string
        default: 'staging'

permissions:
  contents: write

jobs:
  caller_create_feature_branch:
    uses: EngineerincioOrg/Infra_CI_Templates/.github/workflows/reusable-create-feature-branch.yml@main
    secrets:
      JIRA_TOKEN: ${{ secrets.ORG_JIRA_TOKEN }}
      JIRA_USER_EMAIL: ${{ secrets.ORG_JIRA_USER_EMAIL }}
    with:
      jira_key: ${{ inputs.jira_key }}
      base_branch: ${{ inputs.base_branch }}