name: Deploy Website to AWS Amplify

on:
  push:
    branches:
      - staging
      - release/**
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

jobs:
  setup-env-variables:
    name: Get Environment Variables
    runs-on: ubuntu-latest

    env:
      STAGING_ENV_PACK: ${{ vars.STAGING_ENV_PACK }}

    steps:
      - name: 📌 Set Environment Variables
        shell: bash
        run: |
          ENV_PACK=""

          # branch + staging
          if [ "$GITHUB_REF_TYPE" = "branch" ] && [ "$GITHUB_REF_NAME" = "staging" ]; then
            ENV_PACK="${STAGING_ENV_PACK}"
          fi

          # tags -> production
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            ENV_PACK="${PRODUCTION_ENV_PACK}"
          fi

          # Export each KEY=VALUE line as env var
          while IFS='=' read -r key value; do
            [ -z "$key" ] && continue
            echo "$key=$value" >> "$GITHUB_ENV"
          done <<< "$ENV_PACK"

          # Build comma-separated string for Amplify
          ENV_STRING=$(echo "$ENV_PACK" | tr '\n' ',' | sed 's/,$//')
          echo "ENV_STRING=$ENV_STRING" >> "$GITHUB_ENV"

  # caller-deploy:
  #   uses: EngineerincioOrg/Infra_CI_Templates/.github/workflows/reusable-deploy.yml@main
  #   needs: setup-env-variables
  #   with:
  #     node_version: 20
  #     git_sync: true
  #   secrets:
  #     AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     AWS_ARTIFACT_BUCKET: ${{ secrets.AWS_ARTIFACT_BUCKET }}
  #     AWS_AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}
  #     QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  #     STAGING_GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.ORG_STAGING_GOOGLE_CHAT_WEBHOOK_URL }}
  #     PRODUCTION_GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.ORG_PRODUCTION_GOOGLE_CHAT_WEBHOOK_URL }}

