name: Deploy Website to AWS Amplify

on:
  push:
    branches:
      - staging
      - release/**
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

jobs:
  caller-deploy:
    uses: EngineerincioOrg/Infra_CI_Templates/.github/workflows/reusable-deploy.yml@main
    with:
      node_version: 20
      git_sync: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ARTIFACT_BUCKET: ${{ secrets.AWS_ARTIFACT_BUCKET }}
      AWS_AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      STAGING_GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.ORG_STAGING_GOOGLE_CHAT_WEBHOOK_URL }}
      PRODUCTION_GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.ORG_PRODUCTION_GOOGLE_CHAT_WEBHOOK_URL }}