name: Deploy Amplify Preview

on:
  workflow_dispatch:
    inputs:
      jira_task:
        description: 'Jira Key (e.g., DEV-42) to create a branch for.'
        required: true
        type: string

permissions:
  contents: write
  actions: read
  security-events: write
  id-token: write

jobs:
  setup-env-variables:
    name: Get Environment Variables
    runs-on: ubuntu-latest
    outputs:
      env_string: ${{ steps.setup_env.outputs.env_string }}
    env:
      STAGING_ENV_PACK: ${{ vars.STAGING_ENV_PACK }}
      PRODUCTION_ENV_PACK: ${{ vars.PRODUCTION_ENV_PACK }}

    steps:
      - name: 📌 Set Environment Variables
        shell: bash
        id: setup_env
        run: |
          ENV_PACK=""

          # branch + staging
          if [ "$GITHUB_REF_TYPE" = "branch" ] && [ "$GITHUB_REF_NAME" = "staging" ]; then
            ENV_PACK="${STAGING_ENV_PACK}"
          fi

          # tags -> production
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            ENV_PACK="${PRODUCTION_ENV_PACK}"
          fi

          # 1) Clean pack: remove blank lines + Windows \r
          CLEAN_PACK=$(printf '%s\n' "$ENV_PACK" | sed '/^\s*$/d' | tr -d '\r')

          # 2) Print each env (for debug) – *safe*, no secrets here
          while IFS='=' read -r key value; do
            [ -z "$key" ] && continue
            echo "➡️ [Environment variable] $key: $value"
          done <<< "$CLEAN_PACK"

          # 3) Build a single-line comma-separated ENV_STRING
          ENV_STRING=$(printf '%s\n' "$CLEAN_PACK" | paste -sd, -)

          echo "env_string=$ENV_STRING" >> "$GITHUB_OUTPUT"

  caller-preivew-deploy:
    uses: EngineerincioOrg/Infra_CI_Templates/.github/workflows/reusable-preview-deploy.yml@main
    needs: setup-env-variables
    with:
      jira_task: ${{ inputs.jira_task }}
      node_version: 20
      git_sync: true
      environment_vars: ${{ needs.setup-env-variables.outputs.env_string }}
      JIRA_BASE_URL: ${{ vars.ORG_JIRA_BASE_URL }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ARTIFACT_BUCKET: ${{ secrets.AWS_ARTIFACT_BUCKET }}
      AWS_AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      JIRA_TOKEN: ${{ secrets.ORG_JIRA_TOKEN }}
      JIRA_USER_EMAIL: ${{ secrets.ORG_JIRA_USER_EMAIL }}
      STAGING_GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.ORG_STAGING_GOOGLE_CHAT_WEBHOOK_URL }}